apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels: 
   app: vpro-pv
spec:
  capacity:
    storage: 500Mi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  
  hostPath:
    path: "/tmp/data"
  
 
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
