apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: vproapp 
  labels: 
    app: vproapp

spec: 
  selector:
    matchLabels:
      app: vproapp

  replicas: 1

  template:
    metadata: 
      labels:
        app: vproapp

    spec:
     containers:
       - name: vproapp
         image: vprofile/vprofileapp  # or our image " muhammedhamedelgaml/vproapp-image "
         
         resources: 
            limits: 
              memory: "128Mi"
              cpu: "500m"
             
         ports:
           - name: vproapp-port
             containerPort: 8080


     initContainers:  # we need containers of db ,memcache to run first (dependency) , when those containers are complete successfully , main container will be start 
       - name: init-db
         image: busybox # the is lightweight container used to execute commands  
         command: ['sh' , '-c' ,'until nslookup vprodb ; do echo waiting for db ; sleep 2 ; done ;']  
                 # for i in {1..100}; do sleep 1; if nslookup vprodb; then exit 0; fi; done; exit 1  // do the same thing 
       
       - name: init-mem
         image: busybox 
         command: ['sh' , '-c' ,'until nslookup vprocache01 ; do echo waiting for db ; sleep 2 ; done ; ']  
 
