apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  selector:
    matchLabels:
      app: vpro-pv
  resources:
    requests:
      storage: "500Mi"
  accessModes:
    - ReadWriteOnce
